# Generated by Django 4.1.4 on 2022-12-21 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='blogger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('Date', models.DateField()),
                ('Image', models.ImageField(upload_to='')),
                ('Content', models.TextField(max_length=10000)),
            ],
        ),
    ]
